//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtKayitOtomasyon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stirngs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stirngs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YurtKayitOtomasyon.Properties.stirngs", typeof(stirngs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata Oluştu!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı Kullanıcı Adı veya Şifre!.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm İşlemleri.
        /// </summary>
        internal static string LangBOLISL {
            get {
                return ResourceManager.GetString("LangBOLISL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamadan Çık.
        /// </summary>
        internal static string LangCIK {
            get {
                return ResourceManager.GetString("LangCIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim.
        /// </summary>
        internal static string LangErişim {
            get {
                return ResourceManager.GetString("LangErişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Ekle.
        /// </summary>
        internal static string LangGIDEK {
            get {
                return ResourceManager.GetString("LangGIDEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giderler.
        /// </summary>
        internal static string LangGIDER {
            get {
                return ResourceManager.GetString("LangGIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Listesi.
        /// </summary>
        internal static string LangGIDLIST {
            get {
                return ResourceManager.GetString("LangGIDLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Raporları.
        /// </summary>
        internal static string LangGIDRAP {
            get {
                return ResourceManager.GetString("LangGIDRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir Raporları.
        /// </summary>
        internal static string LangGRAP {
            get {
                return ResourceManager.GetString("LangGRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string LangHAKKIM {
            get {
                return ResourceManager.GetString("LangHAKKIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Makinesi.
        /// </summary>
        internal static string LangHESAPM {
            get {
                return ResourceManager.GetString("LangHESAPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstatistikler.
        /// </summary>
        internal static string LangISTATIK {
            get {
                return ResourceManager.GetString("LangISTATIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odalar.
        /// </summary>
        internal static string LangODA {
            get {
                return ResourceManager.GetString("LangODA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Bilgileri.
        /// </summary>
        internal static string LangODAB {
            get {
                return ResourceManager.GetString("LangODAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Al.
        /// </summary>
        internal static string LangODAL {
            get {
                return ResourceManager.GetString("LangODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemeler.
        /// </summary>
        internal static string LangODE {
            get {
                return ResourceManager.GetString("LangODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Bölüm.
        /// </summary>
        internal static string LangOGBOL {
            get {
                return ResourceManager.GetString("LangOGBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenciler.
        /// </summary>
        internal static string LangOGR {
            get {
                return ResourceManager.GetString("LangOGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Devamsızlık.
        /// </summary>
        internal static string LangOGRDEVAM {
            get {
                return ResourceManager.GetString("LangOGRDEVAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Düzenle.
        /// </summary>
        internal static string LangOGRDUZ {
            get {
                return ResourceManager.GetString("LangOGRDUZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Ekle.
        /// </summary>
        internal static string LangOGREK {
            get {
                return ResourceManager.GetString("LangOGREK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci İzin.
        /// </summary>
        internal static string LangOGRIZIN {
            get {
                return ResourceManager.GetString("LangOGRIZIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Listesi.
        /// </summary>
        internal static string LangOGRLIST {
            get {
                return ResourceManager.GetString("LangOGRLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu Kapat.
        /// </summary>
        internal static string LangOturum {
            get {
                return ResourceManager.GetString("LangOturum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Şifre İşlemleri.
        /// </summary>
        internal static string LangPSIFRE {
            get {
                return ResourceManager.GetString("LangPSIFRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel İşlemleri.
        /// </summary>
        internal static string LangPSLEM {
            get {
                return ResourceManager.GetString("LangPSLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre İşlemleri.
        /// </summary>
        internal static string LangSIFRE {
            get {
                return ResourceManager.GetString("LangSIFRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Raporları.
        /// </summary>
        internal static string LangSTRAP {
            get {
                return ResourceManager.GetString("LangSTRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        internal static string LangYON {
            get {
                return ResourceManager.GetString("LangYON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Ad.
        /// </summary>
        internal static string OGRAD {
            get {
                return ResourceManager.GetString("OGRAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Doğum Tarihi.
        /// </summary>
        internal static string OGRDOGUM {
            get {
                return ResourceManager.GetString("OGRDOGUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        internal static string OGRKAYIT {
            get {
                return ResourceManager.GetString("OGRKAYIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Oda No.
        /// </summary>
        internal static string OGRODA {
            get {
                return ResourceManager.GetString("OGRODA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Soyad.
        /// </summary>
        internal static string OGRSOYAD {
            get {
                return ResourceManager.GetString("OGRSOYAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci TC.
        /// </summary>
        internal static string OGRTC {
            get {
                return ResourceManager.GetString("OGRTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Telefon No.
        /// </summary>
        internal static string OGRTEL {
            get {
                return ResourceManager.GetString("OGRTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veli Adı Soyadı.
        /// </summary>
        internal static string OGRVELİ {
            get {
                return ResourceManager.GetString("OGRVELİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu kapatmak istediğinize emin misiniz?.
        /// </summary>
        internal static string oturumsoru {
            get {
                return ResourceManager.GetString("oturumsoru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Giriş Yap.
        /// </summary>
        internal static string S001 {
            get {
                return ResourceManager.GetString("S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldiniz!.
        /// </summary>
        internal static string S002 {
            get {
                return ResourceManager.GetString("S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        internal static string S003 {
            get {
                return ResourceManager.GetString("S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamyı kapatmak istediğinize emin misiniz?.
        /// </summary>
        internal static string uygulamasoru {
            get {
                return ResourceManager.GetString("uygulamasoru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veli Adresi.
        /// </summary>
        internal static string VELADRES {
            get {
                return ResourceManager.GetString("VELADRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veli Telefon Numarası.
        /// </summary>
        internal static string VELTEL {
            get {
                return ResourceManager.GetString("VELTEL", resourceCulture);
            }
        }
    }
}
